/*
 * countries.js — 195 countries with official government visa links
 * Regions: Africa 54, Americas 35, Asia 48, Europe 44, Oceania 14
 * Cyprus, Armenia, Azerbaijan, Georgia → Asia
 * "verify needed" means the official URL could not be confirmed yet
 */
window.JUNI_VISA_COUNTRIES = [
  /* ── Africa (54) ─────────────────────────────────────────────── */
  { flag: "🇩🇿", country: "Algeria", region: "Africa", visa_apply_url: "verify needed" },
  { flag: "🇦🇴", country: "Angola", region: "Africa", visa_apply_url: "https://www.evisa.gov.ao" },
  { flag: "🇧🇯", country: "Benin", region: "Africa", visa_apply_url: "https://evisa.gouv.bj" },
  { flag: "🇧🇼", country: "Botswana", region: "Africa", visa_apply_url: "https://www.evisa.gov.bw" },
  { flag: "🇧🇫", country: "Burkina Faso", region: "Africa", visa_apply_url: "verify needed" },
  { flag: "🇧🇮", country: "Burundi", region: "Africa", visa_apply_url: "verify needed" },
  { flag: "🇨🇻", country: "Cabo Verde", region: "Africa", visa_apply_url: "https://www.evisa.gov.cv" },
  { flag: "🇨🇲", country: "Cameroon", region: "Africa", visa_apply_url: "https://www.evisacam.cm" },
  { flag: "🇨🇫", country: "Central African Republic", region: "Africa", visa_apply_url: "verify needed" },
  { flag: "🇹🇩", country: "Chad", region: "Africa", visa_apply_url: "verify needed" },
  { flag: "🇰🇲", country: "Comoros", region: "Africa", visa_apply_url: "https://www.evisa.gov.km" },
  { flag: "🇨🇬", country: "Congo", region: "Africa", visa_apply_url: "verify needed" },
  { flag: "🇨🇩", country: "Democratic Republic of the Congo", region: "Africa", visa_apply_url: "verify needed" },
  { flag: "🇨🇮", country: "Côte d'Ivoire", region: "Africa", visa_apply_url: "verify needed" },
  { flag: "🇩🇯", country: "Djibouti", region: "Africa", visa_apply_url: "https://www.evisa.gouv.dj" },
  { flag: "🇪🇬", country: "Egypt", region: "Africa", visa_apply_url: "https://www.visa2egypt.gov.eg" },
  { flag: "🇬🇶", country: "Equatorial Guinea", region: "Africa", visa_apply_url: "verify needed" },
  { flag: "🇪🇷", country: "Eritrea", region: "Africa", visa_apply_url: "verify needed" },
  { flag: "🇸🇿", country: "Eswatini", region: "Africa", visa_apply_url: "verify needed" },
  { flag: "🇪🇹", country: "Ethiopia", region: "Africa", visa_apply_url: "https://www.evisa.gov.et" },
  { flag: "🇬🇦", country: "Gabon", region: "Africa", visa_apply_url: "https://www.evisa.gouv.ga" },
  { flag: "🇬🇲", country: "Gambia", region: "Africa", visa_apply_url: "verify needed" },
  { flag: "🇬🇭", country: "Ghana", region: "Africa", visa_apply_url: "verify needed" },
  { flag: "🇬🇳", country: "Guinea", region: "Africa", visa_apply_url: "verify needed" },
  { flag: "🇬🇼", country: "Guinea-Bissau", region: "Africa", visa_apply_url: "verify needed" },
  { flag: "🇰🇪", country: "Kenya", region: "Africa", visa_apply_url: "https://www.etakenya.go.ke" },
  { flag: "🇱🇸", country: "Lesotho", region: "Africa", visa_apply_url: "verify needed" },
  { flag: "🇱🇷", country: "Liberia", region: "Africa", visa_apply_url: "verify needed" },
  { flag: "🇱🇾", country: "Libya", region: "Africa", visa_apply_url: "verify needed" },
  { flag: "🇲🇬", country: "Madagascar", region: "Africa", visa_apply_url: "https://www.evisa.mg" },
  { flag: "🇲🇼", country: "Malawi", region: "Africa", visa_apply_url: "https://www.evisa.gov.mw" },
  { flag: "🇲🇱", country: "Mali", region: "Africa", visa_apply_url: "verify needed" },
  { flag: "🇲🇷", country: "Mauritania", region: "Africa", visa_apply_url: "verify needed" },
  { flag: "🇲🇺", country: "Mauritius", region: "Africa", visa_apply_url: "verify needed" },
  { flag: "🇲🇦", country: "Morocco", region: "Africa", visa_apply_url: "verify needed" },
  { flag: "🇲🇿", country: "Mozambique", region: "Africa", visa_apply_url: "verify needed" },
  { flag: "🇳🇦", country: "Namibia", region: "Africa", visa_apply_url: "verify needed" },
  { flag: "🇳🇪", country: "Niger", region: "Africa", visa_apply_url: "verify needed" },
  { flag: "🇳🇬", country: "Nigeria", region: "Africa", visa_apply_url: "https://www.immigration.gov.ng" },
  { flag: "🇷🇼", country: "Rwanda", region: "Africa", visa_apply_url: "https://www.irembo.gov.rw" },
  { flag: "🇸🇹", country: "São Tomé and Príncipe", region: "Africa", visa_apply_url: "verify needed" },
  { flag: "🇸🇳", country: "Senegal", region: "Africa", visa_apply_url: "verify needed" },
  { flag: "🇸🇨", country: "Seychelles", region: "Africa", visa_apply_url: "https://www.seychelles.govtas.com" },
  { flag: "🇸🇱", country: "Sierra Leone", region: "Africa", visa_apply_url: "verify needed" },
  { flag: "🇸🇴", country: "Somalia", region: "Africa", visa_apply_url: "verify needed" },
  { flag: "🇿🇦", country: "South Africa", region: "Africa", visa_apply_url: "https://www.dha.gov.za" },
  { flag: "🇸🇸", country: "South Sudan", region: "Africa", visa_apply_url: "verify needed" },
  { flag: "🇸🇩", country: "Sudan", region: "Africa", visa_apply_url: "verify needed" },
  { flag: "🇹🇿", country: "Tanzania", region: "Africa", visa_apply_url: "https://www.eservices.immigration.go.tz" },
  { flag: "🇹🇬", country: "Togo", region: "Africa", visa_apply_url: "verify needed" },
  { flag: "🇹🇳", country: "Tunisia", region: "Africa", visa_apply_url: "verify needed" },
  { flag: "🇺🇬", country: "Uganda", region: "Africa", visa_apply_url: "https://www.visas.immigration.go.ug" },
  { flag: "🇿🇲", country: "Zambia", region: "Africa", visa_apply_url: "https://www.evisa.zambiaimmigration.gov.zm" },
  { flag: "🇿🇼", country: "Zimbabwe", region: "Africa", visa_apply_url: "https://www.evisa.gov.zw" },

  /* ── Americas (35) ───────────────────────────────────────────── */
  { flag: "🇦🇬", country: "Antigua and Barbuda", region: "Americas", visa_apply_url: "https://www.immigration.gov.ag" },
  { flag: "🇦🇷", country: "Argentina", region: "Americas", visa_apply_url: "verify needed" },
  { flag: "🇧🇸", country: "Bahamas", region: "Americas", visa_apply_url: "verify needed" },
  { flag: "🇧🇧", country: "Barbados", region: "Americas", visa_apply_url: "verify needed" },
  { flag: "🇧🇿", country: "Belize", region: "Americas", visa_apply_url: "verify needed" },
  { flag: "🇧🇴", country: "Bolivia", region: "Americas", visa_apply_url: "verify needed" },
  { flag: "🇧🇷", country: "Brazil", region: "Americas", visa_apply_url: "https://www.gov.br/mre/pt-br" },
  { flag: "🇨🇦", country: "Canada", region: "Americas", visa_apply_url: "https://www.canada.ca/en/immigration-refugees-citizenship.html" },
  { flag: "🇨🇱", country: "Chile", region: "Americas", visa_apply_url: "verify needed" },
  { flag: "🇨🇴", country: "Colombia", region: "Americas", visa_apply_url: "https://www.cancilleria.gov.co" },
  { flag: "🇨🇷", country: "Costa Rica", region: "Americas", visa_apply_url: "verify needed" },
  { flag: "🇨🇺", country: "Cuba", region: "Americas", visa_apply_url: "verify needed" },
  { flag: "🇩🇲", country: "Dominica", region: "Americas", visa_apply_url: "verify needed" },
  { flag: "🇩🇴", country: "Dominican Republic", region: "Americas", visa_apply_url: "verify needed" },
  { flag: "🇪🇨", country: "Ecuador", region: "Americas", visa_apply_url: "verify needed" },
  { flag: "🇸🇻", country: "El Salvador", region: "Americas", visa_apply_url: "verify needed" },
  { flag: "🇬🇩", country: "Grenada", region: "Americas", visa_apply_url: "verify needed" },
  { flag: "🇬🇹", country: "Guatemala", region: "Americas", visa_apply_url: "verify needed" },
  { flag: "🇬🇾", country: "Guyana", region: "Americas", visa_apply_url: "verify needed" },
  { flag: "🇭🇹", country: "Haiti", region: "Americas", visa_apply_url: "verify needed" },
  { flag: "🇭🇳", country: "Honduras", region: "Americas", visa_apply_url: "verify needed" },
  { flag: "🇯🇲", country: "Jamaica", region: "Americas", visa_apply_url: "https://www.pica.gov.jm" },
  { flag: "🇲🇽", country: "Mexico", region: "Americas", visa_apply_url: "https://www.inm.gob.mx" },
  { flag: "🇳🇮", country: "Nicaragua", region: "Americas", visa_apply_url: "verify needed" },
  { flag: "🇵🇦", country: "Panama", region: "Americas", visa_apply_url: "verify needed" },
  { flag: "🇵🇾", country: "Paraguay", region: "Americas", visa_apply_url: "verify needed" },
  { flag: "🇵🇪", country: "Peru", region: "Americas", visa_apply_url: "verify needed" },
  { flag: "🇰🇳", country: "Saint Kitts and Nevis", region: "Americas", visa_apply_url: "verify needed" },
  { flag: "🇱🇨", country: "Saint Lucia", region: "Americas", visa_apply_url: "https://www.evisa.gov.lc" },
  { flag: "🇻🇨", country: "Saint Vincent and the Grenadines", region: "Americas", visa_apply_url: "verify needed" },
  { flag: "🇸🇷", country: "Suriname", region: "Americas", visa_apply_url: "https://www.evisa.sr" },
  { flag: "🇹🇹", country: "Trinidad and Tobago", region: "Americas", visa_apply_url: "verify needed" },
  { flag: "🇺🇸", country: "United States", region: "Americas", visa_apply_url: "https://travel.state.gov/content/travel/en/us-visas.html" },
  { flag: "🇺🇾", country: "Uruguay", region: "Americas", visa_apply_url: "verify needed" },
  { flag: "🇻🇪", country: "Venezuela", region: "Americas", visa_apply_url: "verify needed" },

  /* ── Asia (48) ───────────────────────────────────────────────── */
  { flag: "🇦🇫", country: "Afghanistan", region: "Asia", visa_apply_url: "verify needed" },
  { flag: "🇦🇲", country: "Armenia", region: "Asia", visa_apply_url: "https://www.evisa.mfa.am" },
  { flag: "🇦🇿", country: "Azerbaijan", region: "Asia", visa_apply_url: "https://www.evisa.gov.az" },
  { flag: "🇧🇭", country: "Bahrain", region: "Asia", visa_apply_url: "https://www.evisa.gov.bh" },
  { flag: "🇧🇩", country: "Bangladesh", region: "Asia", visa_apply_url: "https://www.visa.gov.bd" },
  { flag: "🇧🇹", country: "Bhutan", region: "Asia", visa_apply_url: "https://www.doi.gov.bt" },
  { flag: "🇧🇳", country: "Brunei", region: "Asia", visa_apply_url: "verify needed" },
  { flag: "🇰🇭", country: "Cambodia", region: "Asia", visa_apply_url: "https://www.evisa.gov.kh" },
  { flag: "🇨🇾", country: "Cyprus", region: "Asia", visa_apply_url: "https://www.moi.gov.cy" },
  { flag: "🇬🇪", country: "Georgia", region: "Asia", visa_apply_url: "https://www.evisa.gov.ge" },
  { flag: "🇮🇳", country: "India", region: "Asia", visa_apply_url: "https://www.indianvisaonline.gov.in" },
  { flag: "🇮🇩", country: "Indonesia", region: "Asia", visa_apply_url: "https://www.imigrasi.go.id" },
  { flag: "🇮🇷", country: "Iran", region: "Asia", visa_apply_url: "https://www.evisa.mfa.ir" },
  { flag: "🇮🇶", country: "Iraq", region: "Asia", visa_apply_url: "verify needed" },
  { flag: "🇮🇱", country: "Israel", region: "Asia", visa_apply_url: "https://www.gov.il/he/departments/topics/entryvisas" },
  { flag: "🇯🇵", country: "Japan", region: "Asia", visa_apply_url: "https://www.mofa.go.jp/j_info/visit/visa/" },
  { flag: "🇯🇴", country: "Jordan", region: "Asia", visa_apply_url: "verify needed" },
  { flag: "🇰🇿", country: "Kazakhstan", region: "Asia", visa_apply_url: "https://www.vmp.gov.kz" },
  { flag: "🇰🇼", country: "Kuwait", region: "Asia", visa_apply_url: "verify needed" },
  { flag: "🇰🇬", country: "Kyrgyzstan", region: "Asia", visa_apply_url: "https://www.evisa.kg" },
  { flag: "🇱🇦", country: "Laos", region: "Asia", visa_apply_url: "verify needed" },
  { flag: "🇱🇧", country: "Lebanon", region: "Asia", visa_apply_url: "https://www.general-security.gov.lb" },
  { flag: "🇲🇾", country: "Malaysia", region: "Asia", visa_apply_url: "https://www.imi.gov.my" },
  { flag: "🇲🇻", country: "Maldives", region: "Asia", visa_apply_url: "https://www.immigration.gov.mv" },
  { flag: "🇲🇳", country: "Mongolia", region: "Asia", visa_apply_url: "https://www.evisa.mn" },
  { flag: "🇲🇲", country: "Myanmar", region: "Asia", visa_apply_url: "https://www.evisa.moip.gov.mm" },
  { flag: "🇳🇵", country: "Nepal", region: "Asia", visa_apply_url: "https://www.immigration.gov.np" },
  { flag: "🇰🇵", country: "North Korea", region: "Asia", visa_apply_url: "verify needed" },
  { flag: "🇴🇲", country: "Oman", region: "Asia", visa_apply_url: "https://www.evisa.rop.gov.om" },
  { flag: "🇵🇰", country: "Pakistan", region: "Asia", visa_apply_url: "https://www.onlinevisa.nadra.gov.pk" },
  { flag: "🇵🇸", country: "Palestine", region: "Asia", visa_apply_url: "verify needed" },
  { flag: "🇵🇭", country: "Philippines", region: "Asia", visa_apply_url: "https://www.evisa.gov.ph" },
  { flag: "🇶🇦", country: "Qatar", region: "Asia", visa_apply_url: "https://www.moi.gov.qa" },
  { flag: "🇸🇦", country: "Saudi Arabia", region: "Asia", visa_apply_url: "https://visa.visitsaudi.com" },
  { flag: "🇸🇬", country: "Singapore", region: "Asia", visa_apply_url: "https://www.ica.gov.sg" },
  { flag: "🇰🇷", country: "South Korea", region: "Asia", visa_apply_url: "https://www.k-eta.go.kr" },
  { flag: "🇱🇰", country: "Sri Lanka", region: "Asia", visa_apply_url: "https://www.eta.gov.lk" },
  { flag: "🇸🇾", country: "Syria", region: "Asia", visa_apply_url: "verify needed" },
  { flag: "🇹🇼", country: "Taiwan", region: "Asia", visa_apply_url: "https://www.boca.gov.tw" },
  { flag: "🇹🇯", country: "Tajikistan", region: "Asia", visa_apply_url: "https://www.evisa.tj" },
  { flag: "🇹🇭", country: "Thailand", region: "Asia", visa_apply_url: "https://www.thaievisa.go.th" },
  { flag: "🇹🇱", country: "Timor-Leste", region: "Asia", visa_apply_url: "verify needed" },
  { flag: "🇹🇷", country: "Turkey", region: "Asia", visa_apply_url: "https://www.evisa.gov.tr" },
  { flag: "🇹🇲", country: "Turkmenistan", region: "Asia", visa_apply_url: "verify needed" },
  { flag: "🇦🇪", country: "United Arab Emirates", region: "Asia", visa_apply_url: "https://www.mofa.gov.ae" },
  { flag: "🇺🇿", country: "Uzbekistan", region: "Asia", visa_apply_url: "https://www.e-visa.gov.uz" },
  { flag: "🇻🇳", country: "Vietnam", region: "Asia", visa_apply_url: "https://www.xuatnhapcanh.gov.vn" },
  { flag: "🇾🇪", country: "Yemen", region: "Asia", visa_apply_url: "verify needed" },

  /* ── Europe (44) ────────────────────────────────────────────── */
  { flag: "🇦🇱", country: "Albania", region: "Europe", visa_apply_url: "https://evisa.gov.al" },
  { flag: "🇦🇩", country: "Andorra", region: "Europe", visa_apply_url: "verify needed" },
  { flag: "🇦🇹", country: "Austria", region: "Europe", visa_apply_url: "https://www.bmeia.gv.at" },
  { flag: "🇧🇾", country: "Belarus", region: "Europe", visa_apply_url: "verify needed" },
  { flag: "🇧🇪", country: "Belgium", region: "Europe", visa_apply_url: "https://dofi.ibz.be" },
  { flag: "🇧🇦", country: "Bosnia and Herzegovina", region: "Europe", visa_apply_url: "https://www.mfa.gov.ba" },
  { flag: "🇧🇬", country: "Bulgaria", region: "Europe", visa_apply_url: "https://www.mfa.bg" },
  { flag: "🇭🇷", country: "Croatia", region: "Europe", visa_apply_url: "https://mvep.gov.hr" },
  { flag: "🇨🇿", country: "Czech Republic", region: "Europe", visa_apply_url: "https://www.mzv.cz" },
  { flag: "🇩🇰", country: "Denmark", region: "Europe", visa_apply_url: "https://www.nyidanmark.dk" },
  { flag: "🇪🇪", country: "Estonia", region: "Europe", visa_apply_url: "https://www.politsei.ee" },
  { flag: "🇫🇮", country: "Finland", region: "Europe", visa_apply_url: "https://um.fi" },
  { flag: "🇫🇷", country: "France", region: "Europe", visa_apply_url: "https://france-visas.gouv.fr" },
  { flag: "🇩🇪", country: "Germany", region: "Europe", visa_apply_url: "https://www.auswaertiges-amt.de" },
  { flag: "🇬🇷", country: "Greece", region: "Europe", visa_apply_url: "https://www.mfa.gr" },
  { flag: "🇻🇦", country: "Holy See", region: "Europe", visa_apply_url: "verify needed" },
  { flag: "🇭🇺", country: "Hungary", region: "Europe", visa_apply_url: "https://konzuliszolgalat.kormany.hu" },
  { flag: "🇮🇸", country: "Iceland", region: "Europe", visa_apply_url: "https://www.utl.is" },
  { flag: "🇮🇪", country: "Ireland", region: "Europe", visa_apply_url: "https://www.irishimmigration.ie" },
  { flag: "🇮🇹", country: "Italy", region: "Europe", visa_apply_url: "https://vistoperitalia.esteri.it" },
  { flag: "🇱🇻", country: "Latvia", region: "Europe", visa_apply_url: "https://www.pmlp.gov.lv" },
  { flag: "🇱🇮", country: "Liechtenstein", region: "Europe", visa_apply_url: "verify needed" },
  { flag: "🇱🇹", country: "Lithuania", region: "Europe", visa_apply_url: "https://www.migracija.lrv.lt" },
  { flag: "🇱🇺", country: "Luxembourg", region: "Europe", visa_apply_url: "https://guichet.public.lu" },
  { flag: "🇲🇹", country: "Malta", region: "Europe", visa_apply_url: "https://identita.gov.mt" },
  { flag: "🇲🇩", country: "Moldova", region: "Europe", visa_apply_url: "https://www.evisa.gov.md" },
  { flag: "🇲🇨", country: "Monaco", region: "Europe", visa_apply_url: "verify needed" },
  { flag: "🇲🇪", country: "Montenegro", region: "Europe", visa_apply_url: "https://www.mfa.gov.me" },
  { flag: "🇳🇱", country: "Netherlands", region: "Europe", visa_apply_url: "https://www.netherlandsworldwide.nl" },
  { flag: "🇲🇰", country: "North Macedonia", region: "Europe", visa_apply_url: "verify needed" },
  { flag: "🇳🇴", country: "Norway", region: "Europe", visa_apply_url: "https://www.udi.no" },
  { flag: "🇵🇱", country: "Poland", region: "Europe", visa_apply_url: "https://www.gov.pl/web/diplomacy" },
  { flag: "🇵🇹", country: "Portugal", region: "Europe", visa_apply_url: "https://vistos.mne.gov.pt" },
  { flag: "🇷🇴", country: "Romania", region: "Europe", visa_apply_url: "https://www.evisa.mae.ro" },
  { flag: "🇷🇺", country: "Russia", region: "Europe", visa_apply_url: "https://electronicvisa.kdmid.ru" },
  { flag: "🇸🇲", country: "San Marino", region: "Europe", visa_apply_url: "verify needed" },
  { flag: "🇷🇸", country: "Serbia", region: "Europe", visa_apply_url: "https://www.evisa.gov.rs" },
  { flag: "🇸🇰", country: "Slovakia", region: "Europe", visa_apply_url: "https://www.mzv.sk" },
  { flag: "🇸🇮", country: "Slovenia", region: "Europe", visa_apply_url: "https://www.gov.si" },
  { flag: "🇪🇸", country: "Spain", region: "Europe", visa_apply_url: "https://www.exteriores.gob.es" },
  { flag: "🇸🇪", country: "Sweden", region: "Europe", visa_apply_url: "https://www.migrationsverket.se" },
  { flag: "🇨🇭", country: "Switzerland", region: "Europe", visa_apply_url: "https://www.sem.admin.ch" },
  { flag: "🇺🇦", country: "Ukraine", region: "Europe", visa_apply_url: "https://www.evisa.mfa.gov.ua" },
  { flag: "🇬🇧", country: "United Kingdom", region: "Europe", visa_apply_url: "https://www.gov.uk/standard-visitor" },

  /* ── Oceania (14) ───────────────────────────────────────────── */
  { flag: "🇦🇺", country: "Australia", region: "Oceania", visa_apply_url: "https://immi.homeaffairs.gov.au" },
  { flag: "🇫🇯", country: "Fiji", region: "Oceania", visa_apply_url: "verify needed" },
  { flag: "🇰🇮", country: "Kiribati", region: "Oceania", visa_apply_url: "verify needed" },
  { flag: "🇲🇭", country: "Marshall Islands", region: "Oceania", visa_apply_url: "verify needed" },
  { flag: "🇫🇲", country: "Micronesia", region: "Oceania", visa_apply_url: "verify needed" },
  { flag: "🇳🇷", country: "Nauru", region: "Oceania", visa_apply_url: "verify needed" },
  { flag: "🇳🇿", country: "New Zealand", region: "Oceania", visa_apply_url: "https://www.immigration.govt.nz" },
  { flag: "🇵🇼", country: "Palau", region: "Oceania", visa_apply_url: "verify needed" },
  { flag: "🇵🇬", country: "Papua New Guinea", region: "Oceania", visa_apply_url: "https://www.ica.gov.pg" },
  { flag: "🇼🇸", country: "Samoa", region: "Oceania", visa_apply_url: "verify needed" },
  { flag: "🇸🇧", country: "Solomon Islands", region: "Oceania", visa_apply_url: "verify needed" },
  { flag: "🇹🇴", country: "Tonga", region: "Oceania", visa_apply_url: "verify needed" },
  { flag: "🇹🇻", country: "Tuvalu", region: "Oceania", visa_apply_url: "verify needed" },
  { flag: "🇻🇺", country: "Vanuatu", region: "Oceania", visa_apply_url: "verify needed" }
];
