// 20 more languages + tip texts for the first 5. Order of each array = K.
const K = ["sub","search","clear","hint","r_all","r_africa","r_americas","r_asia","r_europe","r_oceania","apply","note","help","empty","emptyFor","count","f1","f2","f3","tipLink","tipBody","close"];
function add(code, name, rtl, arr) {
  WV_LANGS[code] = name;
  if (rtl) WV_RTL.push(code);
  const o = {};
  K.forEach((k, i) => { o[k] = arr[i]; });
  WV_I18N[code] = o;
}
Object.assign(WV_I18N.en, { tipLink: "Need another language?", tipBody: "Use your browser's Translate: Chrome ⋮ → Translate • Safari aA → Translate • Edge ⋯ → Translate", close: "Close" });
Object.assign(WV_I18N.ur, { tipLink: "کوئی اور زبان؟", tipBody: "براؤزر کا ترجمہ استعمال کریں: Chrome ⋮ → Translate • Safari aA → Translate • Edge ⋯ → Translate", close: "بند کریں" });
Object.assign(WV_I18N.ar, { tipLink: "لغة أخرى؟", tipBody: "استخدم ترجمة المتصفح: Chrome ⋮ → Translate • Safari aA → Translate • Edge ⋯ → Translate", close: "إغلاق" });
Object.assign(WV_I18N.hi, { tipLink: "कोई और भाषा?", tipBody: "ब्राउज़र का अनुवाद इस्तेमाल करें: Chrome ⋮ → Translate • Safari aA → Translate • Edge ⋯ → Translate", close: "बंद करें" });
Object.assign(WV_I18N.fr, { tipLink: "Une autre langue ?", tipBody: "Utilisez la traduction du navigateur : Chrome ⋮ → Traduire • Safari aA → Traduire • Edge ⋯ → Traduire", close: "Fermer" });

add("es","Español",false,["Directorio de solicitud de visa","Buscar país...","Borrar","Elige un país y abre su solicitud de visa o su página oficial de información.","Todos","África","América","Asia","Europa","Oceanía","Abrir solicitud de visa ↗","Consulta el sitio web oficial del gobierno antes de solicitar.","¿El enlace no funciona? Busca el sitio oficial","No se encontró ningún país.",'No se encontró ningún país para "{q}"',"{n} país|{n} países","World Visa • directorio de visas de 195 países","World Visa es un directorio. No es un sitio web del gobierno y no tramita visas.","Consulta siempre el sitio web del gobierno o la embajada del país de destino antes de solicitar.","¿Otro idioma?","Usa el traductor del navegador: Chrome ⋮ → Traducir • Safari aA → Traducir • Edge ⋯ → Traducir","Cerrar"]);
add("pt","Português",false,["Diretório de pedido de visto","Pesquisar país...","Limpar","Escolha um país e abra o pedido de visto ou a página oficial de informações.","Todos","África","Américas","Ásia","Europa","Oceania","Abrir pedido de visto ↗","Confira o site oficial do governo antes de solicitar.","O link não funciona? Procure o site oficial","Nenhum país encontrado.",'Nenhum país encontrado para "{q}"',"{n} país|{n} países","World Visa • diretório de vistos de 195 países","World Visa é um diretório. Não é um site do governo e não processa vistos.","Sempre confira o site do governo ou da embaixada do destino antes de solicitar.","Outro idioma?","Use o tradutor do navegador: Chrome ⋮ → Traduzir • Safari aA → Traduzir • Edge ⋯ → Traduzir","Fechar"]);
add("ru","Русский",false,["Справочник по подаче на визу","Поиск страны...","Очистить","Выберите страну и откройте страницу подачи заявления на визу или официальную информацию.","Все","Африка","Америка","Азия","Европа","Океания","Открыть подачу на визу ↗","Перед подачей проверьте официальный сайт правительства.","Ссылка не работает? Найдите официальный сайт","Страна не найдена.",'Страна не найдена: "{q}"',"{n} страна|{n} страны|{n} стран","World Visa • справочник виз 195 стран","World Visa — справочник. Это не сайт правительства, и он не оформляет визы.","Перед подачей всегда проверяйте сайт правительства или посольства страны назначения.","Другой язык?","Используйте переводчик браузера: Chrome ⋮ → Перевести • Safari aA → Перевести • Edge ⋯ → Перевести","Закрыть"]);
add("zh","中文",false,["签证申请目录","搜索国家...","清除","选择一个国家，打开其签证申请或官方签证信息页面。","全部","非洲","美洲","亚洲","欧洲","大洋洲","打开签证申请 ↗","申请前请查看政府官方网站。","链接打不开？搜索官方网站","未找到国家。",'未找到与"{q}"相关的国家',"{n} 个国家|{n} 个国家","World Visa • 195 个国家的签证目录","World Visa 只是目录，不是政府网站，也不办理签证。","申请前，请务必查看目的地国家政府或使馆网站上的最新要求。","其他语言？","请使用浏览器的翻译功能：Chrome ⋮ → 翻译 • Safari aA → 翻译 • Edge ⋯ → 翻译","关闭"]);
add("bn","বাংলা",false,["ভিসা আবেদন ডিরেক্টরি","দেশ খুঁজুন...","মুছুন","একটি দেশ বেছে নিন এবং তার ভিসা আবেদন বা সরকারি ভিসা তথ্যের পেজ খুলুন।","সব","আফ্রিকা","আমেরিকা","এশিয়া","ইউরোপ","ওশেনিয়া","ভিসা আবেদন খুলুন ↗","আবেদনের আগে সরকারি অফিসিয়াল ওয়েবসাইট দেখে নিন।","লিংক কাজ করছে না? অফিসিয়াল সাইট খুঁজুন","কোনো দেশ পাওয়া যায়নি।",'"{q}" এর জন্য কোনো দেশ পাওয়া যায়নি',"{n}টি দেশ|{n}টি দেশ","ওয়ার্ল্ড ভিসা • 195টি দেশের ভিসা ডিরেক্টরি","ওয়ার্ল্ড ভিসা শুধু একটি ডিরেক্টরি। এটি সরকারি ওয়েবসাইট নয় এবং ভিসা প্রসেস করে না।","আবেদনের আগে সর্বশেষ শর্তের জন্য গন্তব্য দেশের সরকারি বা দূতাবাসের ওয়েবসাইট সবসময় দেখুন।","অন্য ভাষা?","ব্রাউজারের অনুবাদ ব্যবহার করুন: Chrome ⋮ → Translate • Safari aA → Translate • Edge ⋯ → Translate","বন্ধ করুন"]);
add("tr","Türkçe",false,["Vize Başvuru Rehberi","Ülke ara...","Temizle","Bir ülke seçin ve vize başvurusunu veya resmi vize bilgi sayfasını açın.","Tümü","Afrika","Amerika","Asya","Avrupa","Okyanusya","Vize Başvurusunu Aç ↗","Başvurmadan önce resmi hükümet sitesini kontrol edin.","Bağlantı çalışmıyor mu? Resmi siteyi arayın","Ülke bulunamadı.",'"{q}" için ülke bulunamadı',"{n} ülke|{n} ülke","World Visa • 195 ülkelik vize rehberi","World Visa bir rehberdir. Devlet sitesi değildir ve vize işlemi yapmaz.","Başvurmadan önce en güncel şartlar için hedef ülkenin hükümet veya büyükelçilik sitesini her zaman kontrol edin.","Başka dil?","Tarayıcının çeviri özelliğini kullanın: Chrome ⋮ → Çevir • Safari aA → Çevir • Edge ⋯ → Çevir","Kapat"]);
add("id","Bahasa Indonesia",false,["Direktori Pengajuan Visa","Cari negara...","Hapus","Pilih negara lalu buka pengajuan visa atau halaman informasi visa resminya.","Semua","Afrika","Amerika","Asia","Eropa","Oseania","Buka Pengajuan Visa ↗","Periksa situs resmi pemerintah sebelum mengajukan.","Tautan tidak berfungsi? Cari situs resmi","Negara tidak ditemukan.",'Negara tidak ditemukan untuk "{q}"',"{n} negara|{n} negara","World Visa • direktori visa 195 negara","World Visa adalah direktori. Ini bukan situs pemerintah dan tidak memproses visa.","Selalu periksa situs pemerintah atau kedutaan negara tujuan untuk persyaratan terbaru sebelum mengajukan.","Bahasa lain?","Gunakan terjemahan browser: Chrome ⋮ → Terjemahkan • Safari aA → Terjemahkan • Edge ⋯ → Terjemahkan","Tutup"]);
add("de","Deutsch",false,["Visa-Antrags-Verzeichnis","Land suchen...","Leeren","Wähle ein Land und öffne den Visumantrag oder die offizielle Informationsseite.","Alle","Afrika","Amerika","Asien","Europa","Ozeanien","Visumantrag öffnen ↗","Prüfe vor dem Antrag die offizielle Regierungswebsite.","Link funktioniert nicht? Offizielle Seite suchen","Kein Land gefunden.",'Kein Land gefunden für "{q}"',"{n} Land|{n} Länder","World Visa • Visa-Verzeichnis für 195 Länder","World Visa ist ein Verzeichnis. Es ist keine Regierungswebsite und bearbeitet keine Visa.","Prüfe vor dem Antrag immer die Website der Regierung oder Botschaft des Ziellandes.","Andere Sprache?","Nutze die Übersetzung deines Browsers: Chrome ⋮ → Übersetzen • Safari aA → Übersetzen • Edge ⋯ → Übersetzen","Schließen"]);
add("fa","فارسی",true,["فهرست درخواست ویزا","جستجوی کشور...","پاک کردن","یک کشور انتخاب کنید و صفحه درخواست ویزا یا اطلاعات رسمی ویزای آن را باز کنید.","همه","آفریقا","آمریکا","آسیا","اروپا","اقیانوسیه","باز کردن درخواست ویزا ↗","پیش از درخواست، وب‌سایت رسمی دولت را بررسی کنید.","لینک کار نمی‌کند؟ سایت رسمی را جستجو کنید","کشوری پیدا نشد.",'کشوری برای "{q}" پیدا نشد',"{n} کشور|{n} کشور","ورلد ویزا • فهرست ویزای 195 کشور","ورلد ویزا فقط یک فهرست است. وب‌سایت دولتی نیست و ویزا صادر نمی‌کند.","پیش از درخواست، همیشه وب‌سایت دولت یا سفارت کشور مقصد را برای جدیدترین شرایط بررسی کنید.","زبان دیگر؟","از ترجمه مرورگر استفاده کنید: Chrome ⋮ → Translate • Safari aA → Translate • Edge ⋯ → Translate","بستن"]);
add("sw","Kiswahili",false,["Orodha ya Maombi ya Visa","Tafuta nchi...","Futa","Chagua nchi kisha fungua ukurasa wa maombi ya visa au taarifa rasmi za visa.","Zote","Afrika","Amerika","Asia","Ulaya","Oceania","Fungua Maombi ya Visa ↗","Angalia tovuti rasmi ya serikali kabla ya kuomba.","Kiungo hakifanyi kazi? Tafuta tovuti rasmi","Hakuna nchi iliyopatikana.",'Hakuna nchi iliyopatikana kwa "{q}"',"Nchi {n}|Nchi {n}","World Visa • orodha ya visa za nchi 195","World Visa ni orodha tu. Si tovuti ya serikali na haishughulikii visa.","Kabla ya kuomba, angalia kila mara tovuti ya serikali au ubalozi wa nchi unayokwenda kwa masharti mapya.","Lugha nyingine?","Tumia tafsiri ya kivinjari: Chrome ⋮ → Tafsiri • Safari aA → Tafsiri • Edge ⋯ → Tafsiri","Funga"]);
add("it","Italiano",false,["Elenco richieste di visto","Cerca paese...","Cancella","Scegli un paese e apri la richiesta di visto o la pagina ufficiale di informazioni.","Tutti","Africa","Americhe","Asia","Europa","Oceania","Apri richiesta di visto ↗","Controlla il sito ufficiale del governo prima di fare richiesta.","Il link non funziona? Cerca il sito ufficiale","Nessun paese trovato.",'Nessun paese trovato per "{q}"',"{n} paese|{n} paesi","World Visa • elenco visti di 195 paesi","World Visa è un elenco. Non è un sito governativo e non elabora visti.","Controlla sempre il sito del governo o dell'ambasciata del paese di destinazione prima di fare richiesta.","Un'altra lingua?","Usa la traduzione del browser: Chrome ⋮ → Traduci • Safari aA → Traduci • Edge ⋯ → Traduci","Chiudi"]);
add("ja","日本語",false,["ビザ申請ディレクトリ","国を検索...","クリア","国を選んで、ビザ申請ページまたは公式のビザ情報ページを開きます。","すべて","アフリカ","アメリカ","アジア","ヨーロッパ","オセアニア","ビザ申請を開く ↗","申請の前に、政府の公式サイトを確認してください。","リンクが開かない？公式サイトを検索","国が見つかりません。",'「{q}」に一致する国はありません',"{n}か国|{n}か国","World Visa • 195か国のビザディレクトリ","World Visaはディレクトリです。政府のサイトではなく、ビザの処理も行いません。","申請の前に、必ず渡航先の政府または大使館のサイトで最新の要件を確認してください。","他の言語？","ブラウザの翻訳を使ってください：Chrome ⋮ → 翻訳 • Safari aA → 翻訳 • Edge ⋯ → 翻訳","閉じる"]);
add("ko","한국어",false,["비자 신청 디렉터리","국가 검색...","지우기","국가를 선택하고 비자 신청 또는 공식 비자 정보 페이지를 여세요.","전체","아프리카","아메리카","아시아","유럽","오세아니아","비자 신청 열기 ↗","신청 전에 정부 공식 웹사이트를 확인하세요.","링크가 열리지 않나요? 공식 사이트 검색","국가를 찾을 수 없습니다.",'"{q}"에 대한 국가를 찾을 수 없습니다',"{n}개국|{n}개국","World Visa • 195개국 비자 디렉터리","World Visa는 디렉터리입니다. 정부 웹사이트가 아니며 비자를 처리하지 않습니다.","신청 전에 최신 요건을 위해 목적지 국가의 정부 또는 대사관 웹사이트를 항상 확인하세요.","다른 언어?","브라우저의 번역 기능을 사용하세요: Chrome ⋮ → 번역 • Safari aA → 번역 • Edge ⋯ → 번역","닫기"]);
add("vi","Tiếng Việt",false,["Danh bạ xin thị thực","Tìm quốc gia...","Xóa","Chọn một quốc gia và mở trang xin thị thực hoặc trang thông tin thị thực chính thức.","Tất cả","Châu Phi","Châu Mỹ","Châu Á","Châu Âu","Châu Đại Dương","Mở trang xin thị thực ↗","Hãy kiểm tra trang web chính thức của chính phủ trước khi nộp đơn.","Liên kết không hoạt động? Tìm trang chính thức","Không tìm thấy quốc gia.",'Không tìm thấy quốc gia cho "{q}"',"{n} quốc gia|{n} quốc gia","World Visa • danh bạ thị thực 195 quốc gia","World Visa chỉ là danh bạ. Đây không phải trang web của chính phủ và không xử lý thị thực.","Luôn kiểm tra trang web của chính phủ hoặc đại sứ quán nước đến để biết yêu cầu mới nhất trước khi nộp đơn.","Ngôn ngữ khác?","Dùng tính năng dịch của trình duyệt: Chrome ⋮ → Dịch • Safari aA → Dịch • Edge ⋯ → Dịch","Đóng"]);
add("th","ไทย",false,["ไดเรกทอรีสมัครวีซ่า","ค้นหาประเทศ...","ล้าง","เลือกประเทศ แล้วเปิดหน้าสมัครวีซ่าหรือหน้าข้อมูลวีซ่าอย่างเป็นทางการ","ทั้งหมด","แอฟริกา","อเมริกา","เอเชีย","ยุโรป","โอเชียเนีย","เปิดหน้าสมัครวีซ่า ↗","ตรวจสอบเว็บไซต์ทางการของรัฐบาลก่อนสมัคร","ลิงก์ใช้ไม่ได้? ค้นหาเว็บไซต์ทางการ","ไม่พบประเทศ",'ไม่พบประเทศสำหรับ "{q}"',"{n} ประเทศ|{n} ประเทศ","World Visa • ไดเรกทอรีวีซ่า 195 ประเทศ","World Visa เป็นเพียงไดเรกทอรี ไม่ใช่เว็บไซต์ของรัฐบาล และไม่ดำเนินการเรื่องวีซ่า","ก่อนสมัคร โปรดตรวจสอบเว็บไซต์ของรัฐบาลหรือสถานทูตของประเทศปลายทางเพื่อดูข้อกำหนดล่าสุดเสมอ","ภาษาอื่น?","ใช้ฟีเจอร์แปลของเบราว์เซอร์: Chrome ⋮ → แปล • Safari aA → แปล • Edge ⋯ → แปล","ปิด"]);
add("nl","Nederlands",false,["Visumaanvraag-gids","Zoek land...","Wissen","Kies een land en open de visumaanvraag of de officiële informatiepagina.","Alle","Afrika","Amerika","Azië","Europa","Oceanië","Visumaanvraag openen ↗","Controleer de officiële overheidswebsite voordat je aanvraagt.","Werkt de link niet? Zoek de officiële site","Geen land gevonden.",'Geen land gevonden voor "{q}"',"{n} land|{n} landen","World Visa • visumgids voor 195 landen","World Visa is een gids. Het is geen overheidswebsite en verwerkt geen visa.","Controleer altijd de website van de overheid of ambassade van het bestemmingsland voor de nieuwste eisen.","Andere taal?","Gebruik de vertaalfunctie van je browser: Chrome ⋮ → Vertalen • Safari aA → Vertalen • Edge ⋯ → Vertalen","Sluiten"]);
add("pl","Polski",false,["Katalog wniosków wizowych","Szukaj kraju...","Wyczyść","Wybierz kraj i otwórz wniosek wizowy lub oficjalną stronę z informacjami o wizie.","Wszystkie","Afryka","Ameryka","Azja","Europa","Oceania","Otwórz wniosek wizowy ↗","Przed złożeniem wniosku sprawdź oficjalną stronę rządową.","Link nie działa? Wyszukaj oficjalną stronę","Nie znaleziono kraju.",'Nie znaleziono kraju dla „{q}”',"{n} kraj|{n} kraje|{n} krajów","World Visa • katalog wiz dla 195 krajów","World Visa to katalog. Nie jest stroną rządową i nie przetwarza wiz.","Przed złożeniem wniosku zawsze sprawdź stronę rządu lub ambasady kraju docelowego.","Inny język?","Użyj tłumaczenia w przeglądarce: Chrome ⋮ → Tłumacz • Safari aA → Tłumacz • Edge ⋯ → Tłumacz","Zamknij"]);
add("uk","Українська",false,["Довідник подання на візу","Пошук країни...","Очистити","Виберіть країну та відкрийте сторінку подання на візу або офіційну інформацію.","Усі","Африка","Америка","Азія","Європа","Океанія","Відкрити подання на візу ↗","Перед поданням перевірте офіційний сайт уряду.","Посилання не працює? Знайдіть офіційний сайт","Країну не знайдено.",'Країну не знайдено: "{q}"',"{n} країна|{n} країни|{n} країн","World Visa • довідник віз 195 країн","World Visa — це довідник. Це не сайт уряду, і він не оформлює візи.","Перед поданням завжди перевіряйте сайт уряду або посольства країни призначення.","Інша мова?","Скористайтеся перекладачем браузера: Chrome ⋮ → Перекласти • Safari aA → Перекласти • Edge ⋯ → Перекласти","Закрити"]);
add("tl","Filipino",false,["Direktoryo ng Aplikasyon sa Visa","Maghanap ng bansa...","I-clear","Pumili ng bansa at buksan ang aplikasyon sa visa o opisyal na pahina ng impormasyon.","Lahat","Africa","Amerika","Asya","Europa","Oceania","Buksan ang Aplikasyon sa Visa ↗","Tingnan ang opisyal na website ng gobyerno bago mag-apply.","Hindi gumagana ang link? Hanapin ang opisyal na site","Walang nahanap na bansa.",'Walang nahanap na bansa para sa "{q}"',"{n} bansa|{n} bansa","World Visa • direktoryo ng visa ng 195 bansa","Ang World Visa ay direktoryo lamang. Hindi ito website ng gobyerno at hindi ito nagpoproseso ng visa.","Laging tingnan ang website ng gobyerno o embahada ng destinasyon para sa pinakabagong requirements bago mag-apply.","Ibang wika?","Gamitin ang Translate ng browser: Chrome ⋮ → Translate • Safari aA → Translate • Edge ⋯ → Translate","Isara"]);
add("ta","தமிழ்",false,["விசா விண்ணப்ப அடைவு","நாட்டைத் தேடுங்கள்...","அழி","ஒரு நாட்டைத் தேர்ந்தெடுத்து, அதன் விசா விண்ணப்பம் அல்லது அதிகாரப்பூர்வ விசா தகவல் பக்கத்தைத் திறக்கவும்.","அனைத்தும்","ஆப்பிரிக்கா","அமெரிக்கா","ஆசியா","ஐரோப்பா","ஓசியானியா","விசா விண்ணப்பத்தைத் திற ↗","விண்ணப்பிக்கும் முன் அரசின் அதிகாரப்பூர்வ இணையதளத்தைச் சரிபார்க்கவும்.","இணைப்பு வேலை செய்யவில்லையா? அதிகாரப்பூர்வ தளத்தைத் தேடுங்கள்","நாடு எதுவும் கிடைக்கவில்லை.",'"{q}" க்கு நாடு எதுவும் கிடைக்கவில்லை',"{n} நாடு|{n} நாடுகள்","வேர்ல்ட் விசா • 195 நாடுகளின் விசா அடைவு","வேர்ல்ட் விசா ஒரு அடைவு மட்டுமே. இது அரசு இணையதளம் அல்ல; விசாக்களைச் செயலாக்குவதில்லை.","விண்ணப்பிக்கும் முன் சமீபத்திய தேவைகளுக்கு, சேருமிட நாட்டின் அரசு அல்லது தூதரக இணையதளத்தை எப்போதும் பார்க்கவும்.","வேறு மொழி?","உலாவியின் மொழிபெயர்ப்பைப் பயன்படுத்துங்கள்: Chrome ⋮ → Translate • Safari aA → Translate • Edge ⋯ → Translate","மூடு"]);
